CREATE NONCLUSTERED INDEX IX_QueueItem_MainQueryIndex ON dbo.QueueItem
	(
	QueueWorkerId,
	State,
	Tries,
	ExecuteTimeNext
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO