CREATE UNIQUE NONCLUSTERED INDEX UX_QueueWorker_Name ON dbo.QueueWorker
	(
	Name
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO